version: '3'

services:

    #db:
    #    image: postgres:13.0-alpine
    #    volumes:
    #        - postgres_data:/var/lib/postgresql/data/
    #    env_file:
    #        - .env
    #    container_name: did_django_schedule_jobs_v2_db_prod
    #    networks:
    #        - main_prod

    fultang:
      image: "${FULTANG_IMAGE}"
      restart: always
      #command: gunicorn did_django_schedule_jobs_v2.wsgi:application --bind 0.0.0.0:8000
      #volumes:
      #    - static_volume:/home/app/web/staticfiles
      #    - media_volume:/home/app/web/mediafiles
      ports:
          - "8009:8009"
      env_file:
          - .env
      #depends_on:
      #    - db
      networks:
          - fultang
      container_name: fultang


networks:
    fultang:
        driver: bridge