from rest_framework_simplejwt.views import TokenObtainPairView
from polyclinic.serializers.token_obtain_pair_serializers import CustomTokenObtainPairSerializer

class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer
