
export const AppRoutesPaths = {
    notFound: "*",
    adminHomePage: "/admin/home",
    welcomePage: "/",
    loginPage: "/login",
    pharmacyPage:"/pharmacy",
    doctorPage: "/doctor",
    laboratoryAssistantPage: "/laboratoryAssistant",
    receptionistPage: "/receptionist/patients",
    cashierPage: "/cashier",
    consultationsList: "/cashier/consultationsList",
    examsList: "/cashier/examsList",
    financialReport: "/cashier/financialReport",
    specialistPage: "/specialist",
    nursePage:"/nurse/patients",
    nurseMedicalStaffsPage: "/nurse/medicalStaffs",
    consultationHistoryPage: "/nurse/patients/consultationHistory/:id",
    helpCenterPage: "/helpCenter",
    patientDetailsPage:"/nurse/patients/patientDetails/:id",
    receptionistMedicalStaffsPage: "/receptionist/medicalStaffs",
    appointmentsPage: "/receptionist/appointments",
}
