
export const AppRoutesPaths = {
    notFound: "*",
    adminHomePage: "/admin/home",
    welcomePage: "/",
    loginPage: "/login",
    forgottenPasswordPage: "/forgotten-password",
    pharmacyPage:"/pharmacy",
    doctorPage: "/doctor",
    laboratoryAssistantPage: "/laboratory-assistant",
    receptionistPage: "/receptionist/patients",
    cashierPage: "/cashier/consultation-list",
    consultationsList: "/cashier/consultations-list",
    examsList: "/cashier/exams-list",
    financialReport: "/cashier/financial-report",
    specialistPage: "/specialist",
    nursePage:"/nurse/patients",
    nurseMedicalStaffsPage: "/nurse/medical-staff",
    consultationHistoryPage: "/nurse/patients/consultation-history/:id",
    helpCenterPage: "/help-center",
    patientDetailsPage:"/nurse/patients/patient-details/:id",
    receptionistMedicalStaffsPage: "/receptionist/medical-staffs",
    appointmentsPage: "/receptionist/appointments",
    adminPatientListPage: "/admin/patient-list",
    addMedicalStaff: "/admin/add-medical-staff",
    adminMedicalStaffListPage: "/admin/medical-staff-list",
    adminConsultationListPage: "/admin/consultation-list",
    adminAppointmentsListPage: "/admin/appointments-list",
    adminExamsListPage: "/admin/exams-list",
    adminHospitalRoomPage: "/admin/room-list",
    adminFinancialReportsPage: "/admin/financial-report",
    accountantPage: "/accountant",
    adminConsultationDetailsPage: "/admin/consultation-list/details",
}
