# Generated by Django 4.2 on 2025-10-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstaff',
            name='accessLevel',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Lead', 'Lead'), ('Staff', 'Staff')], default='Staff', max_length=20),
        ),
    ]
