# Generated by Django 4.2 on 2025-01-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('polyclinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='operation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.financialoperation'),
            preserve_default=False,
        ),
    ]
