# Generated by Django 4.2 on 2024-11-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='cniNumber',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
