# Generated by Django 4.2 on 2025-02-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='requirements',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
