# Generated by Django 4.2 on 2025-03-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0002_alter_appointment_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cniNumber',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
