# Generated by Django 4.2 on 2025-02-02 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polyclinic', '0002_rename_medicaloperator_bill_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='idMedicalStaffGiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_give', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='idMedicalStaffSender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_send', to=settings.AUTH_USER_MODEL),
        ),
    ]
