# Generated by Django 4.2 on 2025-01-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0002_bill_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='paymentStatus',
            field=models.CharField(choices=[('Invalid', 'Invalid'), ('Valid', 'Valid')], default='Invalid', max_length=100),
        ),
    ]
