# Generated by Django 4.2 on 2024-12-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0002_alter_medicalstaff_cninumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstaff',
            name='address',
            field=models.CharField(blank=True, default='Yaounde - damas', max_length=255),
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='birthDate',
            field=models.DateField(blank=True, default='1982-01-01', null=True),
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='phoneNumber',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='cniNumber',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cniNumber',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='condition',
            field=models.CharField(choices=[('NoCritical', 'NoCritical'), ('Critical', 'Critical')], default='NoCritical', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='firstName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastName',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='service',
            field=models.CharField(choices=[('Generalist', 'Generalist'), ('Specialist', 'Specialist'), ('All', 'All')], default='Generalist', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientaccess',
            name='lostAt',
            field=models.DateTimeField(blank=True),
        ),
    ]
