# Generated by Django 4.2 on 2025-01-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0002_bill_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='isAccounted',
            field=models.BooleanField(default=False),
        ),
    ]
