# Generated by Django 4.2 on 2025-03-28 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polyclinic', '0003_alter_patient_cninumber_alter_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolyclinicProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='polyclinic.polyclinicproductcategory')),
            ],
            options={
                'verbose_name_plural': 'PolyclinicProductCategories',
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='PolyclinicProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('current_stock', models.IntegerField(default=0)),
                ('min_stock_level', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock'), ('Discontinued', 'Discontinued'), ('Expiring Soon', 'Expiring Soon')], default='Available', max_length=20)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_medication', models.BooleanField(default=False)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='polyclinic.polyclinicproductcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PolyclinicInventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('expired', 'Expired')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polyclinic.bill')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polyclinic.prescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='polyclinic.polyclinicproduct')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='billitem',
            name='medicament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polyclinic.polyclinicproduct'),
        ),
        migrations.AlterField(
            model_name='prescriptiondrug',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyclinic.polyclinicproduct'),
        ),
        migrations.DeleteModel(
            name='Medicament',
        ),
    ]
