# Generated by Django 4.2 on 2025-01-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0003_alter_consultation_paymentstatus'),
        ('polyclinic', '0003_bill_isaccounted'),
    ]

    operations = [
    ]
