# Generated by Django 4.2 on 2025-03-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0004_polyclinicproductcategory_polyclinicproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cniNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
