# Generated by Django 4.2 on 2025-02-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0004_billitem_description_billitem_unityprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
