# Generated by Django 4.2 on 2025-01-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0004_remove_consultation_consultationtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalfolder',
            name='lastModificationDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
