# Generated by Django 4.2 on 2025-01-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0004_merge_20250127_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polyclinic.medicalstaff'),
            preserve_default=False,
        ),
    ]
