# Generated by Django 4.2 on 2025-01-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0005_alter_medicalfolder_lastmodificationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='arterialPressure',
            new_name='bloodPressure',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='idParameters',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='previousHistory',
        ),
        migrations.AddField(
            model_name='parameters',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='chronicalDiseases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='currentMedication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='familyMedicalHistory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='heartRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='surgeries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='skinAppearance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
