# Generated by Django 4.2 on 2025-02-03 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0006_alter_bill_billcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='idMedicalFolderPage',
        ),
        migrations.RemoveField(
            model_name='prescriptiondrug',
            name='dose',
        ),
        migrations.AddField(
            model_name='prescription',
            name='idConsultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polyclinic.consultation'),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='dosage',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='duration',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='frequency',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='instructions',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
