# Generated by Django 4.2 on 2025-02-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0006_remove_prescription_idmedicalfolderpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptiondrug',
            name='dose',
        ),
    ]
