# Generated by Django 4.2 on 2025-01-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0007_rename_remark_medicalfolderpage_diagnostic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='idMedicnalFolder',
            new_name='idMedicalFolder',
        ),
    ]
