# Generated by Django 4.2 on 2025-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0007_remove_prescriptiondrug_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='examFile',
            field=models.FileField(blank=True, null=True, upload_to='exam_results/'),
        ),
    ]
