# Generated by Django 4.2 on 2025-02-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0007_remove_prescription_idmedicalfolderpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billCode',
            field=models.CharField(max_length=355),
        ),
    ]
