# Generated by Django 4.2 on 2025-01-04 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0008_rename_idmedicnalfolder_patient_idmedicalfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfolderpage',
            name='idMedicalStaff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
