# Generated by Django 4.2 on 2025-02-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0008_examresult_examfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examrequest',
            old_name='examDetails',
            new_name='examName',
        ),
        migrations.RemoveField(
            model_name='examrequest',
            name='idMedicalFolderPage',
        ),
        migrations.AddField(
            model_name='examrequest',
            name='idConsultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polyclinic.consultation'),
        ),
        migrations.AlterField(
            model_name='examrequest',
            name='idExam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polyclinic.exam'),
        ),
    ]
