# Generated by Django 4.2 on 2025-01-05 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0009_medicalfolderpage_idmedicalstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='consultationCost',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='idMedicalStaff',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='consultationtype',
            name='name',
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultationPrice',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='consultation',
            name='idMedicalStaffGiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_give', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='idMedicalStaffSender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_send', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='paymentStatus',
            field=models.CharField(default='invalid', max_length=100),
        ),
        migrations.AddField(
            model_name='consultation',
            name='state',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='consultationtype',
            name='typeDoctor',
            field=models.CharField(choices=[('Specialist', 'Specialist'), ('Ophtalmologist', 'Ophtalmologist'), ('Dentist', 'Dentist')], default='Specialist', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='consultationReason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='idMedicalFolderPage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polyclinic.medicalfolderpage'),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='role',
            field=models.CharField(choices=[('NoRole', 'NoRole'), ('Doctor', 'Doctor'), ('Receptionist', 'Receptionist'), ('Admin', 'Admin'), ('Accountant', 'Accountant'), ('Nurse', 'Nurse'), ('Labtech', 'Labtech'), ('HRM', 'HRM'), ('Pharmacist', 'Pharmacist'), ('Cashier', 'Cashier')], default='NoRole', max_length=20),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='bloodPressure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
