# Generated by Django 4.2 on 2025-02-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0009_rename_examdetails_examrequest_examname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrequest',
            name='idExam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polyclinic.exam'),
        ),
    ]
