# Generated by Django 4.2 on 2025-02-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0010_alter_examrequest_idexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrequest',
            name='examName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
