# Generated by Django 4.2 on 2025-01-25 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('polyclinic', '0011_rename_medicamentname_medicament_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='idPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyclinic.patient'),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='medicalstaff_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='medicalstaff',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='medicalstaff_permissions_set', to='auth.permission'),
        ),
    ]
