# Generated by Django 4.2 on 2025-01-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassCompte',
            new_name='Account',
        ),
        migrations.RemoveField(
            model_name='accountstate',
            name='classCompte',
        ),
        migrations.RemoveField(
            model_name='financialoperation',
            name='classCompte',
        ),
        migrations.AddField(
            model_name='accountstate',
            name='Account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialoperation',
            name='Account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.account'),
            preserve_default=False,
        ),
    ]
