# Generated by Django 4.2 on 2025-02-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit'), ('creance', 'creance')], max_length=255, null=True),
        ),
    ]
