# Generated by Django 4.2 on 2025-03-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountstate',
            old_name='soldePrevu',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='accountstate',
            name='soldeReel',
        ),
    ]
